version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11-stretch


workflows:
  version: 2

  build-and-test:
    jobs:
      - build


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}
      - run: sudo apt-get update
      - run: sudo npm install -g npm
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}
      - run:
          name: run lint check
          command: npm run lint
      - run:
          name: run tests
          command: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .
